### ISSUE TITLE
[question] Refactor to follow Java Code Conventions & Clean Code?

### ISSUE THREAD

**Issue by rsoesemann** [financialforcedev/fflib-apex-common-builder#4]
@jondavis9898 before I can write Readmes or blog posts I first need to learn how to use our builders. Since you extended them I was still using my Base class in all my products. I started doing this today ;-)

I know the most of the code was contributed by you and I respect other persons style in open source projects but nonetheless I want to ask if you mind if I change the following things to make the code more readable:

1. Remove overly verbose comments, that don't add anything to the code
2. Remove C++ style variable prefixes like `m_` to show something is a member  
3. Adjust naming and style to Java conventions that tools like PMD enforce

**Comment by jondavis9898** [comment]
@up2go-rsoesemann Awesome to hear you're using the common builder!!  Very interested to learn how it goes as you progress.  Regarding your questions:

1) Can you provide some specifics around which comments you'd like to remove?  Definitely OK with removing comments that don't provide any value, just want to make sure we're leaving enough for future contributors and those that use the builders to understand enough about the code without having to "read the code."  I'm guessing this is what you're goaling towards, just would like to understand a few examples of where you feel things are too verbose before we collectively pull the plug.  

2) I followed the pattern from fflib_SObjectUnitOfWork since that was the last fflib work that I contributed to.  My thinking was to remain consistent with the rest of the fflib* libraries.  That said, I just did a quick look throughout the rest of fflib common and it appears there is a mixture of usage of "m_" - some use it, some don't.  Short story - I'm cool with removing "m_" since we won't be inconsistent by not applying it since it's usage is already inconsistent.  If we do remove it, I'd recommend we log a ticket in the other fflib's to remove as well where possible (some members are protected so wouldn't be able to remove in those cases without causing backwards compat issues).

3) Can you provide some examples of naming/style changes that you'd like to make?  I'm cool with adhering to PMD assuming the goal is to make all of fflib adhere (at least over time).  I think the priority should be consistency throughout the fflib suite of tools/libraries if that makes sense but definitely on-board with PMD if that's the general direction across the board.

**Comment by rsoesemann** [comment]
@jondavis9898 after I use the class a bit and understand how it works I will PR a "cleaned" version. 

In general the code is way to verbose to me. There is no need to add a funny "give em back" comment above each return or explain put a // mark it as built over a method called markAsBuilt. 

Same for naming. I think we don't need Javadoc type comments to explain 5 line methods. But I guess that just my opinion. I can't enforce all this rules for all the fflib but I hope they will eventually use PMD which will enforce it.

**Comment by jondavis9898** [comment]
As you can tell, I'm a strong believer in comments - too often code doesn't contain enough or very little making it incredibly difficult to maintain/support/enhance.  That said, agreed that obvious lines of code don't need comments especially where the line itself is self-descriptive (e.g. markAsBuilt) but I do feel that every method (at a minimum all non-private methods) should have a comment header block describing it's purpose, params, etc.  Look forward to reviewing your PR :)

**Comment by ImJohnMDaniel** [comment]
@up2go-rsoesemann - FWIW, I agree with @jondavis9898 that every public method should have a comment block describing purpose, params, etc.
